type CaisseType = {
  String: String;
  ID: string;
  DATE: string;
  N_PCE: number;
  TYPE_PCE: string;
  AFFAIRE: string;
  FARDE: string;
  StringENTIFIANT: string;
  LIBELLE: string;
  TX: number;
  CAISSE_USD: number;
  CAISSE_EUR: number;
  TOTAL_USD: number;
  CTRL: string;
  N_FCT: string;
  CAISSE: string;
  REMARQUES: string;
};
export type { CaisseType };
